spring.application.name=mobile

server.port=8081

spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.vpuoayauyubkfvonhezg
spring.datasource.password=mobile2026sherif
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect